### PR TITLE
add this because i don't wanna keep coping and pasting this

### PR DESCRIPTION
**Pull request by McJonnycat**
i added the GJKeys because i don't wanna keep coping and pasting

### CODE REVIEW

**Comment by JuniorNovoa1** [comment]
"coping"

**Comment by beeanie** [comment]
> "coping"

STOP FOLLOWING MY RESPATORYS

**Comment by beeanie** [comment]
and also i wanted to add this instead of copying and paste thing the lines of code

**Comment by JuniorNovoa1** [comment]
> and also i wanted to add this instead of copying and paste thing the lines of code

ik its very annoying i don't get why they don't leave it blank instead lol

**Comment by McJonnycat** [comment]
yeah if they can add this it could be better

**Comment by TentaRJ** [comment]
> > and also i wanted to add this instead of copying and paste thing the lines of code
> 
> ik its very annoying i don't get why they don't leave it blank instead lol

I left it blank so people would read the instructions on how to set it up properly and not berate me with questions.

**Comment by McJonnycat** [comment]
oh ok

**Pull request closed without merging**
